name: Release to Modrinth

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to release (e.g., v2.9.0+1.21.9)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository at tag
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build and publish to Modrinth
        run: ./gradlew build publishModrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: Release ${{ inputs.tag }}
          body_path: CHANGELOG.md
          files: |
            build/libs/*.jar
            !build/libs/*-sources.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}